spring.application.name=ms-validacao-Email
server.port=8082

abstract.api.key=dcac2c78df394f76862dba431bdc8831
abstract.api.url=https://emailreputation.abstractapi.com/v1/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
